/**
 * Central SEO + site metadata. See LAUNCH.md for verification-code setup.
 */

export const SITE = {
  // Primary canonical URL (no trailing slash)
  url: "https://besttintedsunscreen.com",
  name: "Best Tinted Sunscreen",
  tagline: "Independent reviews of Korean and tinted mineral sunscreens",
  description:
    "Independent editorial reviews of Korean sunscreens and tinted mineral SPFs. We test every product on real skin and rank them honestly.",

  // For Organization / Publisher schema
  logo: "/logo-og.png", // generated by scripts/generate-og.mjs
  founded: "2026",

  // Social handles (optional, used in Organization sameAs)
  social: {
    twitter: "",  // e.g. "@besttintedsun"
    instagram: "", // e.g. "besttintedsunscreen"
    pinterest: "",
  },
} as const;

/**
 * Search-engine verification codes. Paste the `content="..."` value only.
 * Empty string = meta tag is omitted. See LAUNCH.md for provider URLs.
 */
export const VERIFICATION = {
  googleSiteVerification: "", // e.g. "abc123xyz"
  bingSiteVerification: "",
  yandexVerification: "",
  pinterestVerification: "",
} as const;

/**
 * IndexNow key — must match the filename of public/<key>.txt and the KEY
 * constant in scripts/indexnow.mjs. Regenerate with `openssl rand -hex 32`.
 */
export const INDEXNOW_KEY = "a8f9e2c7d1b4f6e8a2c5d9f3b7e1a4c8";
